SELECT * FROM FONAVI.GSEC_USUARIO;

DESCRIBE FONAVI.GSEC_USUARIO;


SELECT USC_D_USUARIO, USC_D_PASSWORD, USC_E_REGISTRO
FROM FONAVI.GSEC_USUARIO
WHERE USC_D_USUARIO = 'SYSADMIN' AND PDD_C_TIPUSR = 427;
