-------------------------FIN - Tabla SFSOP_CONTROL_REQUERIMIENTO --------------------------------------------


create table SOPORTE.SFSOP_CONTROL_REQUERIMIENTO
(
    CCREQ_C_ID                   NUMBER(10) not null
        primary key,
    CCREQ_D_AREA_ASIGNADA        VARCHAR2(255 char),
    CCREQ_F_FECHA_CREACION       DATE,
    CCREQ_F_FECHA_MODIFICACION   DATE,
    CCREQ_F_FECHA_SOLICITUD      DATE       not null,
    CCREQ_C_USU_REG              NUMBER,
    CCREQ_D_CODIGO_REQ           VARCHAR2(255),
    CCREQ_D_TIPO_REQ             VARCHAR2(255),
    CCREQ_D_TIPO_REQ_DATOS       VARCHAR2(255),
    CCREQ_D_TIPO_SOLICITUD       VARCHAR2(255),
    CCREQ_D_APP                  VARCHAR2(255),
    CCREQ_D_VERSION_APP          VARCHAR2(255),
    CCREQ_D_ESTADO_REQ           VARCHAR2(255),
    CCREQ_D_ASIGNADO             VARCHAR2(255),
    CCREQ_D_SOLICITANTE          VARCHAR2(255),
    CCREQ_C_USU_MOD              NUMBER,
    CCREQ_D_SOLICITUD            VARCHAR2(255 char),
    CCREQ_D_USUARIO_MODIFICADO     VARCHAR2(255 char),
    CCREQ_D_USUARIO_CREACION     VARCHAR2(255 char),
    CCREQ_D_REQUERIMIENTO        CLOB,
    CCREQ_AMB_F_FECH_SOL_QA      DATE,
    CCREQ_AMB_F_FECH_DESPL_QA    DATE,
    CCREQ_AMB_D_RESPO_QA         VARCHAR2(255),
    CCREQ_AMB_D_EJE_PRU_QA       VARCHAR2(255),
    CCREQ_AMB_F_FECH_CTRL_CAL_QA DATE,
    CCREQ_AMB_F_FECH_SOL_PROD    DATE,
    CCREQ_AMB_F_FECH_DESPL_PROD  DATE,
    CCREQ_AMB_D_RESP_PROD        VARCHAR2(255),
    CCREQ_D_TIPO_PASE_PROD       VARCHAR2(50)
)
/
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_C_ID is 'NUMERO AUTOINCREMENTABLE';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_AREA_ASIGNADA is 'ÁREA ASIGNADA ';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_F_FECHA_CREACION is 'FECHA DE CREACIÓN DEL REQUERIMIENTO';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_F_FECHA_MODIFICACION is 'FECHA DE MODIFICACIÓN DEL REQUERIMIENTO';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_C_USU_REG is 'USUARIO QUIEN CREA';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_CODIGO_REQ is 'CODIGO DE REQUERIMIENTO';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_TIPO_REQ is 'TIPO DE REQUERIMIENTO';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_TIPO_REQ_DATOS is 'TIPO DE REQUERIMIENTO DE DATOS';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_TIPO_SOLICITUD is 'TIPO DE MODALIDAD DE PASE A PRODUCCION DE DATOS';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_APP is 'NOMBRE DE LA APLICACIÓN';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_VERSION_APP is 'VERSIÓN DE LA APLICACIÓN';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_ESTADO_REQ is 'ESTADO DEL REQUERIMIENTO';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_ASIGNADO is 'PROFESIONAL A QUIEN HA SIDO ASIGANDI';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_SOLICITANTE is 'SOLICITANTE DEL REQUERIMIEN';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_C_USU_MOD is 'USUARIO QUIIEN MODIFICA';
comment on column SOPORTE.SFSOP_CONTROL_REQUERIMIENTO.CCREQ_D_TIPO_PASE_PROD is 'TIPO DE MODALIDAD DE PASE  A PRODUCCION DE DATOS (PPD)';

CREATE SEQUENCE  SOPORTE.SEQ_CONTROL_REQUERIMIENTO_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-------------------------FIN - Tabla SFSOP_CONTROL_REQUERIMIENTO --------------------------------------------
------------ TABLA SFSOP_DOCUMENTACION  -------------------------------
create table SOPORTE.SFSOP_DOCUMENTACION
(
    DOC_C_ID_DOC      NUMBER not null
        constraint FK_DOC_ID_DOC
            primary key,
    DOC_D_DESCRIPCION NVARCHAR2(255),
    DOC_C_ESTADO      NUMBER,
    DOC_F_FECH_REG    DATE,
    DOC_F_FECH_MOD    DATE,
    DOC_D_USU_REG     NUMBER,
    DOC_D_USU_MOD     NUMBER,
    DOC_D_TIPO_DOC    NUMBER,
    DOC_C_TIPO_DOCU   NUMBER(10)
)
/
comment on column SOPORTE.SFSOP_DOCUMENTACION.DOC_C_ID_DOC is 'ID correlativo';
comment on column SOPORTE.SFSOP_DOCUMENTACION.DOC_D_DESCRIPCION is 'Descripcion de los documentos y entregables';
comment on column SOPORTE.SFSOP_DOCUMENTACION.DOC_C_ESTADO is 'Estado 1 = Activo y 0 = Inactivo';
comment on column SOPORTE.SFSOP_DOCUMENTACION.DOC_F_FECH_REG is 'Fecha de Registro';
comment on column SOPORTE.SFSOP_DOCUMENTACION.DOC_F_FECH_MOD is 'Fecha de Modificación';
comment on column SOPORTE.SFSOP_DOCUMENTACION.DOC_D_USU_REG is 'Usuario de Registro';
comment on column SOPORTE.SFSOP_DOCUMENTACION.DOC_D_USU_MOD is 'Usuario Modificador';
comment on column SOPORTE.SFSOP_DOCUMENTACION.DOC_D_TIPO_DOC is 'Tipo de documento 1 = Documentos , 2 = Entregables';

-- Creación de secuencia para la tabla documentación
CREATE SEQUENCE SOPORTE.SEQ_DOC_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- Documentos
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Acta de Capacitación', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Acta de Conformidad del Usuario', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Acta de Monitoreo', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Acta de Pase a Producción', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Acta de Pruebas del Software', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Acta de Revisión de Análisis de Software', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Acta de Revisión de Diseño de Software', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Acta de Revisión del Requerimiento', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Documento de Análisis de Software', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Documento de Diseño de Software', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Documento de Plan de Prubeas', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Formato de Requerimiento del Usuario', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Manual de Usuario', 1, SYSDATE, SYSDATE, 1);
INSERT INTO SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Pruebas Funcionales', 1, SYSDATE, SYSDATE, 1);
-- Entregables
INSERT INTO  SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Script', 1, SYSDATE, SYSDATE, 2);
INSERT INTO  SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Ejecutable', 1, SYSDATE, SYSDATE, 2);
INSERT INTO  SOPORTE.SFSOP_DOCUMENTACION(DOC_C_ID_DOC, DOC_D_DESCRIPCION, DOC_C_ESTADO, DOC_F_FECH_REG, DOC_F_FECH_MOD, DOC_D_TIPO_DOC) VALUES (SOPORTE.SEQ_DOC_ID.nextval, 'Fuente', 1, SYSDATE, SYSDATE, 2);
/
--------------------------FIN Tabla SFSOP_DOCUMENTACION --------------------------------------
-------------------------Tabla SFSOP_REQUERIMIENTO_DOCUMENTACION --------------------------------------------
CREATE table SOPORTE.SFSOP_REQUERIMIENTO_DOCUMENTACION
(
    REQDOC_C_ID                   NUMBER not null
        primary key,
    REQ_C_ID                      NUMBER
        constraint FK_REQUEDOCU_CONTROL_REQUERIMIENTO
            references SFSOP_CONTROL_REQUERIMIENTO,
    DOC_C_ID                      NUMBER
        constraint FK_REQUEDOCU_DOCUMENTACION
            references SFSOP_DOCUMENTACION,
    REQDOC_C_ESTADO               NUMBER not null,
    REQDOC_F_FECHA_CREACION       DATE,
    REQDOC_F_FECHA_MODIFICACION   DATE,
    REQDOC_C_USUARIO_CREACION     NUMBER,
    REQDOC_C_USUARIO_MODIFICACION NUMBER
)
/
CREATE SEQUENCE SOPORTE.SEQ_REQDOC_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-------------------------FIN Tabla SFSOP_REQUERIMIENTO_DOCUMENTACION --------------------------------------------

-------------------------Tabla SFSOP_TIPO_SOLICITUDES --------------------------------------------

create table SOPORTE.SFSOP_TIPO_SOLICITUDES
(
    TIPSOL_C_ID             NUMBER not null
        primary key,
    TIPSOL_D_DESCRIPCION    VARCHAR2(150),
    TIPSOL_F_FECHA_CREACION DATE
)
/

INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Atención de requerimientos', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Asesoría Técnica', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Actualizar datos de persona', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Actualizar DB Calidad (QA)', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Actualización DB Desarrollo', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'CAS - Agregar convocatoria', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Intranet Aprendizaje', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Intranet Control Interno', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Intranet RRHH', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Intranet Sifonavi', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'F0/F1', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'F2 - Eliminar carga', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Generar reporte de datos', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'MASS - Mesa de ayuda de sistemas', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Menu Botones', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'SAAU/SAUI', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'SIMA', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Simular Grupo de Pago', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'SIPA - Sistema de pago', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'STD - Sistema Trámite Documentario', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'SGD - Sistema de gestión documental', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'PCI - Pre Cuenta  Individual', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Portal GOB.PE', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Portal SIFONAVI', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Portal WEB', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Procesar Fuentes Externas', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Proceso de Pago', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'PTE - Portal de transparencia', sysdate);
INSERT INTO SOPORTE.SFSOP_TIPO_SOLICITUDES (TIPSOL_C_ID, TIPSOL_D_DESCRIPCION, TIPSOL_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOSOLICITUDES_ID.nextval, 'Otros', sysdate);


CREATE SEQUENCE SOPORTE.SEQ_TIPOSOLICITUDES_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
-------------------------FIN - Tabla SFSOP_TIPO_SOLICITUDES --------------------------------------------

-------------------------Tabla SFSOP_ROL --------------------------------------------
create table SOPORTE.SFSOP_ROL
(
    ROL_C_ID                   NUMBER not null
        primary key,
    ROL_D_DESCRIPCION          VARCHAR2(150),
    ROL_C_ESTADO               NUMBER,
    ROL_F_FECHA_CREACION       DATE default NULL,
    ROL_C_USUARIO_CREACION     NUMBER,
    ROL_F_FECHA_MODIFICACION   DATE,
    ROL_C_USUARIO_MODIFICACION NUMBER
)
/

CREATE SEQUENCE SOPORTE.SEQ_ROL_ID
    START WITH 1
    INCREMENT BY  1
    NOCACHE ;
-- INSERT
INSERT INTO SOPORTE.SFSOP_ROL (ROL_C_ID, ROL_D_DESCRIPCION, ROL_C_ESTADO, ROL_F_FECHA_CREACION, ROL_C_USUARIO_CREACION, ROL_F_FECHA_MODIFICACION, ROL_C_USUARIO_MODIFICACION) VALUES (SOPORTE.SEQ_ROL_ID.nextval, 'ADMINISTRADOR', 1, TIMESTAMP '2023-08-16 16:48:06', null, TIMESTAMP '2023-12-04 14:34:25', null);
INSERT INTO SOPORTE.SFSOP_ROL (ROL_C_ID, ROL_D_DESCRIPCION, ROL_C_ESTADO, ROL_F_FECHA_CREACION, ROL_C_USUARIO_CREACION, ROL_F_FECHA_MODIFICACION, ROL_C_USUARIO_MODIFICACION) VALUES (SOPORTE.SEQ_ROL_ID.nextval, 'ASIGNADO', 1, TIMESTAMP '2023-08-16 16:48:20', null, TIMESTAMP '2023-12-04 15:12:30', null);
INSERT INTO SOPORTE.SFSOP_ROL (ROL_C_ID, ROL_D_DESCRIPCION, ROL_C_ESTADO, ROL_F_FECHA_CREACION, ROL_C_USUARIO_CREACION, ROL_F_FECHA_MODIFICACION, ROL_C_USUARIO_MODIFICACION) VALUES (SOPORTE.SEQ_ROL_ID.nextval, 'USUARIO', 1, TIMESTAMP '2023-08-17 12:55:12', null, TIMESTAMP '2023-12-04 15:12:27', null);
INSERT INTO SOPORTE.SFSOP_ROL (ROL_C_ID, ROL_D_DESCRIPCION, ROL_C_ESTADO, ROL_F_FECHA_CREACION, ROL_C_USUARIO_CREACION, ROL_F_FECHA_MODIFICACION, ROL_C_USUARIO_MODIFICACION) VALUES (SOPORTE.SEQ_ROL_ID.nextval, 'QA', 1, TIMESTAMP '2023-11-29 11:49:57', null, TIMESTAMP '2023-12-05 11:36:23', null);

-------------------------FIN Tabla SFSOP_ROL --------------------------------------------
-------------------------Tabla SFSOP_SOLICITUDES --------------------------------------------


create table SOPORTE.SFSOP_SOLICITUDES
(
    SOL_C_ID                   NUMBER not null
        primary key,
    SOL_D_CODIGO               VARCHAR2(255),
    SOL_F_FECHA_CREACION       DATE,
    SOL_C_CATEGORIA            NUMBER,
    SOL_C_TIPO_SOLICITUD       NUMBER
        constraint FK_TIPO_SOLICITUD
            references SFSOP_TIPO_SOLICITUDES,
    SOL_C_ESTADO               NUMBER,
    SOL_C_PRIORIDAD            VARCHAR2(50),
    SOL_F_FECHA_MODIFICACION   DATE,
    SOL_A_ARCHIVO              BLOB,
    SOL_D_USUARIO_CREACION     VARCHAR2(100),
    SOL_D_USUARIO_MODIFICACION VARCHAR2(100),
    SOL_D_ASIGNADO             VARCHAR2(100),
    SOL_D_DESCRIPCION          CLOB,
    SOL_D_COMENTARIO           CLOB,
    SOL_D_APLICACION           VARCHAR2(255 char),
    SOL_D_FASE                 VARCHAR2(255 char),
    SOL_D_PASE_REQUERIMIENTO   VARCHAR2(255 char),
    SOL_D_VERSION              VARCHAR2(255 char)
)
/
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_C_ID is 'Id';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_D_CODIGO is 'Codigo de la solicitud';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_F_FECHA_CREACION is 'Fecha de creación';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_C_CATEGORIA is 'Categoria';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_C_TIPO_SOLICITUD is 'Tipo de solicitud';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_C_ESTADO is 'Estado';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_C_PRIORIDAD is 'Prioridad Alta, Media y Baja';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_F_FECHA_MODIFICACION is 'Fecha de modificación';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_A_ARCHIVO is 'Archivo adjunto';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_D_USUARIO_CREACION is 'Usuario creado';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_D_USUARIO_MODIFICACION is 'Usuario modificado';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_D_ASIGNADO is 'Asignacion de atencion de las solicitudes';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_D_DESCRIPCION is 'Descripcion';
comment on column SOPORTE.SFSOP_SOLICITUDES.SOL_D_COMENTARIO is 'Comentario';

CREATE SEQUENCE SOPORTE.SEQ_SOLICITUDES_ID
    START WITH 1
    INCREMENT BY  1
    NOCACHE ;

-------------------------FIN Tabla SFSOP_SOLICITUDES --------------------------------------------


-----------Alter Tabla USUARIO_FONAVI---------------------------
ALTER TABLE SFSOP_USUARIO_FONAVI
    ADD (
        --USR_D_CONTRASENA VARCHAR2(60),
        USR_D_CONTRATO   VARCHAR2(60)
        );
-- COPIAR LOS DATOS DE USR_D_CLAVE a USU_D_CONTRASENA
-- UPDATE SFSOP_USUARIO_FONAVI
-- SET USR_D_CONTRASENA = USR_D_CLAVE;

UPDATE SOPORTE.SFSOP_USUARIO_FONAVI
SET
    USR_D_EMAIL                = 'desarrollo01@stfonavi.gob.pe',
    USR_D_TELEFONO             = '99999999',
    USR_D_CLAVE           = '123456',
    USR_D_CONTRATO             = 'LOCADOR'
WHERE USR_C_ID = 141;

-----------------------FIN DE ALTE TABLE-----------------------------------------------
-----------------------TABLE USUARIO ROL-----------------------------------------------

create table SOPORTE.SFSOP_USUARIO_ROL
(
    USROL_C_ID                   NUMBER(10) not null
        primary key,
    ROL_C_ID                     NUMBER(10)
        constraint FK_USUARIO_ROL_ROL
            references SFSOP_ROL,
    USR_C_ID                     NUMBER(19)
        constraint FK_USUARIO_ROL_USUARIO
            references SFSOP_USUARIO_FONAVI,
    USROL_C_ESTADO               NUMBER(10) not null,
    USROL_F_FECHA_CREACION       TIMESTAMP(6),
    USROL_F_FECHA_MODIFICACION   TIMESTAMP(6),
    USROL_C_USUARIO_CREACION     NUMBER(10),
    USROL_C_USUARIO_MODIFICACION NUMBER(10)
)
/

CREATE SEQUENCE SOPORTE.SEQ_USUARIO_ROL
    START WITH 1
    INCREMENT BY 1
    NOCACHE ;
-- INSERT USUARIO ROL
INSERT INTO SOPORTE.SFSOP_USUARIO_ROL (USROL_C_ID, ROL_C_ID, USR_C_ID, USROL_C_ESTADO, USROL_F_FECHA_CREACION, USROL_F_FECHA_MODIFICACION, USROL_C_USUARIO_CREACION, USROL_C_USUARIO_MODIFICACION) VALUES (SOPORTE.SEQ_USUARIO_ROL.NEXTVAL, 1, 141, 1, TIMESTAMP '2024-05-28 16:35:28.090000', TIMESTAMP '2024-05-28 16:35:28.090000', null, null);
INSERT INTO SOPORTE.SFSOP_USUARIO_ROL (USROL_C_ID, ROL_C_ID, USR_C_ID, USROL_C_ESTADO, USROL_F_FECHA_CREACION, USROL_F_FECHA_MODIFICACION, USROL_C_USUARIO_CREACION, USROL_C_USUARIO_MODIFICACION) VALUES (SOPORTE.SEQ_USUARIO_ROL.NEXTVAL, 2, 141, 1, TIMESTAMP '2024-05-28 16:35:28.102000', TIMESTAMP '2024-05-28 16:35:28.102000', null, null);
INSERT INTO SOPORTE.SFSOP_USUARIO_ROL (USROL_C_ID, ROL_C_ID, USR_C_ID, USROL_C_ESTADO, USROL_F_FECHA_CREACION, USROL_F_FECHA_MODIFICACION, USROL_C_USUARIO_CREACION, USROL_C_USUARIO_MODIFICACION) VALUES (SOPORTE.SEQ_USUARIO_ROL.NEXTVAL, 3, 141, 1, TIMESTAMP '2024-05-28 16:35:28.102000', TIMESTAMP '2024-05-28 16:35:28.102000', null, null);
INSERT INTO SOPORTE.SFSOP_USUARIO_ROL (USROL_C_ID, ROL_C_ID, USR_C_ID, USROL_C_ESTADO, USROL_F_FECHA_CREACION, USROL_F_FECHA_MODIFICACION, USROL_C_USUARIO_CREACION, USROL_C_USUARIO_MODIFICACION) VALUES (SOPORTE.SEQ_USUARIO_ROL.NEXTVAL, 4, 141, 1, TIMESTAMP '2024-05-28 16:35:28.103000', TIMESTAMP '2024-05-28 16:35:28.103000', null, null);


---------------- CREATE TABLE SFSOP_APP -----------------------------------
create table SOPORTE.SFSOP_TIPO_APP
(
    TIPAPP_C_ID             NUMBER(10) not null
        primary key,
    TIPAPP_D_DESCRIPCION    VARCHAR2(255 char),
    TIPAPP_F_FECHA_CREACION TIMESTAMP(6)
)
/

CREATE SEQUENCE SOPORTE.SEQ_TIPOAPP_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE ;

INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'BENEFICIADOS', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'F0/F1', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'F1', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'GOB.PE', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'HEREDEROS', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'INTRANET APRENDIZAJE', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'INTRANET CONTROL INTERNO', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'MASS', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'PORTAL BOTONES ', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'MPAGO', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'MPAGO_NET', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'PCI', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'PORTAL SIFONAVI', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'PORTAL WEB', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'POWER APPS', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'PROJU', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'PTE', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SAAU', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SAAU/SAUI', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SACI', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SACI/SAUI', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SAUI', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVI', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC1', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC2', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC3', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC4', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC5', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC6', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC7', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC8', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIFONAVIC9', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SIPA', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'SISTEMAS', SYSDATE);
INSERT INTO SOPORTE.SFSOP_TIPO_APP (TIPAPP_C_ID, TIPAPP_D_DESCRIPCION, TIPAPP_F_FECHA_CREACION) VALUES (SOPORTE.SEQ_TIPOAPP_ID.NEXTVAL, 'STD', SYSDATE);

----------------FIN CREATE TABLE SFSOP_APP -----------------------------------
COMMIT;

---------------------------------------------------------------------------